
spring.datasource.url=jdbc:postgresql://localhost:5433/gestorCafe
spring.datasource.username=postgres
spring.datasource.password=root

# Configuración de Hibernate (DDL-auto)
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Especificar dialecto de PostgreSQL (Opcional, Spring Boot suele detectarlo)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=default
spring.devtools.restart.enabled=false
spring.devtools.add-properties=false